package com.lgh.dao;

import com.lgh.pojos.Sysrole;

public interface SysroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysrole
     *
     * @mbggenerated Thu Dec 29 23:42:01 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysrole
     *
     * @mbggenerated Thu Dec 29 23:42:01 CST 2016
     */
    int insert(Sysrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysrole
     *
     * @mbggenerated Thu Dec 29 23:42:01 CST 2016
     */
    int insertSelective(Sysrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysrole
     *
     * @mbggenerated Thu Dec 29 23:42:01 CST 2016
     */
    Sysrole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysrole
     *
     * @mbggenerated Thu Dec 29 23:42:01 CST 2016
     */
    int updateByPrimaryKeySelective(Sysrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysrole
     *
     * @mbggenerated Thu Dec 29 23:42:01 CST 2016
     */
    int updateByPrimaryKey(Sysrole record);
}