package com.lgh.pojos;

public class Sysrole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysrole.id
     *
     * @mbggenerated Fri Dec 30 00:07:45 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysrole.rolename
     *
     * @mbggenerated Fri Dec 30 00:07:45 CST 2016
     */
    private String rolename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysrole.id
     *
     * @return the value of sysrole.id
     *
     * @mbggenerated Fri Dec 30 00:07:45 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysrole.id
     *
     * @param id the value for sysrole.id
     *
     * @mbggenerated Fri Dec 30 00:07:45 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysrole.rolename
     *
     * @return the value of sysrole.rolename
     *
     * @mbggenerated Fri Dec 30 00:07:45 CST 2016
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysrole.rolename
     *
     * @param rolename the value for sysrole.rolename
     *
     * @mbggenerated Fri Dec 30 00:07:45 CST 2016
     */
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }
}