package com.lgh.pojos;

public class Sysuser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.id
     *
     * @mbggenerated Fri Dec 30 00:07:45 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.username
     *
     * @mbggenerated Fri Dec 30 00:07:45 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.password
     *
     * @mbggenerated Fri Dec 30 00:07:45 CST 2016
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.id
     *
     * @return the value of sysuser.id
     *
     * @mbggenerated Fri Dec 30 00:07:45 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.id
     *
     * @param id the value for sysuser.id
     *
     * @mbggenerated Fri Dec 30 00:07:45 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.username
     *
     * @return the value of sysuser.username
     *
     * @mbggenerated Fri Dec 30 00:07:45 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.username
     *
     * @param username the value for sysuser.username
     *
     * @mbggenerated Fri Dec 30 00:07:45 CST 2016
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.password
     *
     * @return the value of sysuser.password
     *
     * @mbggenerated Fri Dec 30 00:07:45 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.password
     *
     * @param password the value for sysuser.password
     *
     * @mbggenerated Fri Dec 30 00:07:45 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }
}